@startuml

participant ":Controller" as Controller

participant ":SimulationView" as SimulationView

participant ":TimeManager" as TimeManager
participant ":DroneStateStore" as DroneStateStore
participant ":DroneView" as DroneView


'Animation startet (& läuft)-------------------------------------------'


'start simulation-view'

group loop (timecounter)

Controller -> SimulationView : setEditorTime(timecounter)

activate SimulationView
SimulationView -> TimeManager : setEditorTime(timecounter)
activate TimeManager
SimulationView <<-- TimeManager
deactivate TimeManager

SimulationView->SimulationView : drawChanges()
activate SimulationView
SimulationView->TimeManager : getCurrentEditorTime()
activate TimeManager
SimulationView <<-- TimeManager : time
deactivate TimeManager

SimulationView -> Controller : requestFrameData(time)
SimulationView <<-- Controller : frameData


SimulationView -> DroneStateStore : update(modifiedDrones)
activate DroneStateStore
DroneStateStore -> DroneView : render()
activate DroneView
DroneStateStore <<-- DroneView
deactivate DroneView
SimulationView <<-- DroneStateStore
deactivate DroneStateStore

SimulationView -->> SimulationView
deactivate SimulationView

Controller <<-- SimulationView
deactivate SimulationView

end
'ende simulation-view'



@enduml