@startuml
skinparam style strictuml
' syncronous send: ->
' asyncronous send: ->>
' syncronous return: -->
' asyncronous return: -->>


participant ":Controller" as Controller

participant ":SimulationView" as SimulationView
participant ":SelectionManager" as SelectionManager
participant ":CollisionManager" as CollisionManager
participant ":TimeManager" as TimeManager
participant ":VisibilityManager" as VisibilityManager

participant ":SceneRenderer" as SceneRenderer

activate Controller
Controller -> SimulationView

activate SimulationView

SimulationView->SimulationView : drawChanges()
activate SimulationView


SimulationView -> Controller : getData()
SimulationView <<-- Controller : data


SimulationView -> SelectionManager : applyFrameChanges(currentFrame)
activate SelectionManager
SimulationView <<-- SelectionManager : modifiedFrame
deactivate SelectionManager


SimulationView -> CollisionManager : applyFrameChanges(currentFrame)
activate CollisionManager
SimulationView <<-- CollisionManager : modifiedFrame
deactivate CollisionManager



SimulationView -> TimeManager : applyFrameChanges(currentFrame)
activate TimeManager
SimulationView <<-- TimeManager : modifiedFrame
deactivate TimeManager

SimulationView -> VisibilityManager : applyFrameChanges(currentFrame)
activate VisibilityManager
SimulationView <<-- VisibilityManager : modifiedFrame
deactivate VisibilityManager

SimulationView -> SceneRenderer : render(modifiedFrame)
activate SceneRenderer
SimulationView <<-- SceneRenderer
deactivate SceneRenderer


SimulationView -->> SimulationView
deactivate SimulationView
Controller <<-- SimulationView
deactivate SimulationView

@enduml