@startuml

participant ":Controller" as Controller

participant ":SimulationView" as SimulationView
participant ":SelectionManager" as SelectionManager
participant ":DroneStateStore" as DroneStateStore
participant ":DroneView" as DroneView
participant ":PathStateStore" as PathStateStore
participant ":PathView" as PathView

'Drone auswählen-------------------------------------------'


'start simulation-view'
Controller -> SimulationView : selectDrone(id)

activate SimulationView
SimulationView -> SelectionManager : selectDrone(id)
activate SelectionManager
SimulationView <<-- SelectionManager
deactivate SelectionManager

SimulationView->SimulationView : drawChanges()
activate SimulationView
SimulationView -> Controller : requestFrameData(time)
SimulationView <<-- Controller : frameData
SimulationView -> SelectionManager : applyDroneChanges(currentDroneFrame)
activate SelectionManager
SimulationView <<-- SelectionManager : modifiedDrones
deactivate SelectionManager

SimulationView -> SelectionManager : applyPathChanges(currentPathFrame)
activate SelectionManager
SimulationView <<-- SelectionManager : modifiedPath
deactivate SelectionManager


SimulationView -> DroneStateStore : update(modifiedDrones)
activate DroneStateStore
DroneStateStore -> DroneView : render()
activate DroneView
DroneStateStore <<-- DroneView
deactivate DroneView
SimulationView <<-- DroneStateStore
deactivate DroneStateStore

SimulationView -> PathStateStore : update(modifiedPath)
activate PathStateStore

PathStateStore -> PathView : render()
activate PathView
PathStateStore <<-- PathView
deactivate PathView
SimulationView <<-- PathStateStore
deactivate PathStateStore
SimulationView -->> SimulationView
deactivate SimulationView


Controller <<-- SimulationView
deactivate SimulationView

'ende simulation-view'





'unselect Drone ----------------------------------------'

'start simulation-view'
Controller -> SimulationView : unselectDrone(id)

activate SimulationView
SimulationView -> SelectionManager : unselectDrone(id)
activate SelectionManager
SimulationView <<-- SelectionManager
deactivate SelectionManager

SimulationView->SimulationView : drawChanges()
activate SimulationView
SimulationView -> Controller : requestFrameData(time)
SimulationView <<-- Controller : frameData
SimulationView -> SelectionManager : applyDroneChanges(currentDroneFrame)
activate SelectionManager
SimulationView <<-- SelectionManager : modifiedDrones
deactivate SelectionManager

SimulationView -> SelectionManager : applyPathChanges(currentPathFrame)
activate SelectionManager
SimulationView <<-- SelectionManager : modifiedPath
deactivate SelectionManager


SimulationView -> DroneStateStore : update(modifiedDrones)
activate DroneStateStore
DroneStateStore -> DroneView : render()
activate DroneView
DroneStateStore <<-- DroneView
deactivate DroneView
SimulationView <<-- DroneStateStore
deactivate DroneStateStore

SimulationView -> PathStateStore : update(modifiedPath)
activate PathStateStore

PathStateStore -> PathView : render()
activate PathView
PathStateStore <<-- PathView
deactivate PathView
SimulationView <<-- PathStateStore
deactivate PathStateStore
SimulationView -->> SimulationView
deactivate SimulationView


Controller <<-- SimulationView
deactivate SimulationView

'ende simulation-view'

@enduml