@startuml
skinparam style strictuml
' syncronous send: ->
' asyncronous send: ->>
' syncronous return: -->
' asyncronous return: -->>


participant ":Controller" as Controller

participant ":SimulationView" as SimulationView

participant ":TimeManager" as TimeManager
participant ":LightStateStore" as LightStateStore
participant ":SceneRenderer" as SceneRenderer


'Simulationszeit wird geändert--------------------------------------

'start simulation-view'
Controller -> SimulationView : setSimulationTime(time)

activate SimulationView
SimulationView -> TimeManager : setSimulationTime(time)
activate TimeManager
SimulationView <<-- TimeManager
deactivate TimeManager

SimulationView->SimulationView : drawChanges()
activate SimulationView
SimulationView -> Controller : requestFrameData(time)
SimulationView <<-- Controller : frameData
SimulationView -> TimeManager : applyLightChanges(currentLightFrame)
activate TimeManager
SimulationView <<-- TimeManager : modifiedLight
deactivate TimeManager


SimulationView -> LightStateStore : update(modifiedLight)
activate LightStateStore
LightStateStore -> SceneRenderer : render()
activate SceneRenderer
LightStateStore <<-- SceneRenderer
deactivate SceneRenderer
SimulationView <<-- LightStateStore
deactivate LightStateStore

SimulationView -->> SimulationView
deactivate SimulationView


Controller <<-- SimulationView
deactivate SimulationView

'ende simulation-view'

@enduml