image: node:25

stages:
  - test

cache:
  key: npm-cache
  paths:
    - .npm/

test:
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - npm test -- --watchAll=false --ci --reporters=default --reporters=jest-junit --coverage
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - coverage/
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  rules:
    - when: always