image: node:25

stages:
    - test

cache:
    key: npm-cache
    paths:
        - .npm/

unit-test:
    stage: test
    script:
        - npm ci --cache .npm --prefer-offline
        - npm test -- --watchAll=false --ci --reporters=default --reporters=jest-junit --coverage
    artifacts:
        when: always
        reports:
            junit: junit.xml
        paths:
            - coverage/
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"

e2e-test:
    stage: test
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    script:
        - npm ci
        - npx playwright test
    rules:
        - when: always
