@startuml name Rendering Pipeline
' =====================================================
' Class Diagram: JSX Rendering & Interaction Layer
' =====================================================

skinparam stereotypeCBackgroundColor #EEF
skinparam stereotypeCBorderColor #335
skinparam classAttributeIconSize 0


' -----------------------------------------------------
' SceneRenderer: initializes camera, light, updates
' -----------------------------------------------------
class SceneRenderer <<JSX Component>> {
  + initLight()
  + initCamera()
}

' -----------------------------------------------------
' JSX Objects
' -----------------------------------------------------
class DroneView <<JSX Component>> {
  + props: TODO

  + render(): JSX.Element
}

class KeyFramePathView <<JSX Component>> {
  + props: TODO

  + render(): JSX.Element
}


' -----------------------------------------------------
' Relationships (rendering hierarchy)
' -----------------------------------------------------
SceneRenderer --> DroneView : renders
SceneRenderer --> KeyFramePathView : renders

@enduml
