@startuml name Class Diagram: ISimulation + Subsystems
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100
' =====================================================
' Class Diagram: ISimulation + Subsystems
' =====================================================

class IController

' ISimulation – the central interface (Facade)
class ISimulation {

  - droneStore : DroneStateStore
  - pathStore : PathStateStore
  - lightStore : LightStateStore

  + ISimulation(drone : DroneStateStore, path : PathStateStore, light : LightStateStore)

  + notifyChange()
  + setEditorTime(time : number)
  + setSimulationTime(time : number)
  + selectDrone(id : number)
  + unselectDrone(id : number)
  + notifyCollisionChange(newCollision : Collision)

  + RequestDroneFrame(time : number) : DroneFrame
  + RequestKeyFrames() : PathFrame
}

' Subsystems – internal logic
class TimeManager {
  - currentEditorTime : number
  - chosenLight : LightFrame

  + setEditorTime(time: number)
  + setSimulationTime(time: number)
  + getCurrentEditorTime() : number
  + applyLightChanges(currentLight : Lightframe) : LightFrame

}



class SelectionManager {
  - selectedIds : number[]

  + applyPathChanges(currentPathFrame : PathFrame, allPaths : PathFrame) : PathFrame
  + applyDroneChanges(currentDroneFrame : DroneFrame) : DroneFrame

  + selectDrone(id: number)
  + unselectDrone(id : number)
}

class CollisionManager {
  -currentCollision : Collision

  + applyPathChanges(currentPathFrame : PathFrame, allPaths : PathFrame) : PathFrame
  + applyDroneChanges(currentDroneFrame : DroneFrame) : DroneFrame

  + notifyCollisionChange(newCollision : Collision)
}


' Relationships: Delegation from ISimulation to subsystems
ISimulation " " -- "1 \n timeManager" TimeManager : delegates request >
ISimulation " " -- "1 \n selectionManager" SelectionManager : delegates request >
ISimulation " " -- "1 \n collisionManager" CollisionManager : delegates request >

ISimulation "1" -- "1 \n controller" IController : request data >

@enduml
